services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/autocaravaneandoNGINX/${INICIALES}nginxautocaravaneando
      args:
        - INICIALES=${INICIALES}
    container_name: ${CONTENEDOR}
    image: ${FIRMA}/autocaravaneandonginx
    ports:
      - ${PORT_NODE}:3000
      - ${PORT_WWW}:80
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      pnautocaravaneando:
        ipv4_address: ${IP_WEB}
networks:
  pnautocaravaneando:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}