services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/autocaravaneando/${INICIALES}ubautocaravaneando
      args:
        - INICIALES=${INICIALES}
    container_name: ${CONTENEDOR}
    image: ${FIRMA}/reactautocaravaneando
    ports:
      - ${PORT_NODE}:3000
      - ${PORT_WWW}:80
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      pnginx_network:
        ipv4_address: ${IP_WEB}
networks:
  pnginx_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}